name: Auto Test Step 1 - ClearML Dataset Upload

on:
  push:
    branches: [main]  # ✅ 每次 push 到 main 分支都会自动触发

jobs:
  test_step1:
    runs-on: ubuntu-latest

    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gdown  # Step 1 用到 gdown

      - name: Debug ENV
        run: |
          echo "CLEARML_API_HOST=$CLEARML_API_HOST"
          curl -I $CLEARML_API_HOST

      - name: Run Step 1 - Upload dataset artifact
        run: python step1_dataset_artifact.py
