name: Run ClearML Pipeline v2

on:
  push:
    branches: [master]  # ✅ 自动触发（你当前分支是 master）

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install xgboost gdown nltk

      - name: Debug ENV
        run: |
          echo "CLEARML_API_HOST=$CLEARML_API_HOST"
          curl -I $CLEARML_API_HOST

      - name: Run full pipeline (v2)
        run: python main.py